export const FORM_STEPS = [
  {
    id: 'Step 1',
    name: 'Basic Information',
    title: 'Basic Tour Details',
    description: 'Start with essential information about your tour',
    fields: [
      +'title',
      +'images',
      +'shortDescription',
      +'description',
      'isBestSeller',
      +'location',
      +'durationDays',
      +'categoryIds',
      +'accommodations',
    ],
  },
  {
    id: 'Step 2',
    name: 'Pricing Options',
    title: 'Tour Pricing',
    description: 'Set up different pricing tiers for your tour',
    fields: ['price'],
  },
  {
    id: 'Step 3',
    name: 'Itinerary',
    title: 'Tour Program',
    description: 'Create a detailed day-by-day program',
    fields: ['program'],
  },
  {
    id: 'Step 4',
    name: 'Media Gallery',
    title: 'Tour Images',
    description: 'Upload attractive visuals for your tour',
    fields: ['images'],
  },
  {
    id: 'Step 5',
    name: 'Inclusions & Exclusions',
    title: "What's Included",
    description: "Specify what's included and excluded in the tour package",
    fields: ['inclusions', 'exclusions'],
  },
  {
    id: 'Step 6',
    name: 'Review & Submit',
    title: 'Review Your Tour',
    description: 'Review all details before publishing',
    fields: [],
  },
];
